/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";
import * as LabelDefs from "../../com/atproto/label/defs.defs.js";
import * as ThemeBasic from "./theme/basic.defs.js";

const $nsid = "site.standard.publication";

export { $nsid };

/** A publication record representing a blog, website, or content platform. Publications serve as containers for documents and define the overall branding and settings. */
type Main = {
  $type: "site.standard.publication";

  /**
   * Base publication url (ex: https://standard.site). The canonical document URL is formed by combining this value with the document path.
   */
  url: l.UriString;

  /**
   * Square image to identify the publication. Should be at least 256x256.
   */
  icon?: l.BlobRef;

  /**
   * Name of the publication.
   */
  name: string;

  /**
   * Self-label values for this publication. Effectively content warnings.
   */
  labels?: l.$Typed<LabelDefs.SelfLabels> | l.Unknown$TypedObject;

  /**
   * Simplified publication theme for tools and apps to utilize when displaying content.
   */
  basicTheme?: ThemeBasic.Main;

  /**
   * Brief description of the publication.
   */
  description?: string;

  /**
   * Object containing platform specific preferences (with a few shared properties).
   */
  preferences?: Preferences;
};

export type { Main };

/** A publication record representing a blog, website, or content platform. Publications serve as containers for documents and define the overall branding and settings. */
const main = l.record<"tid", Main>(
  "tid",
  $nsid,
  l.object({
    url: l.string({ format: "uri" }),
    icon: l.optional(l.blob({ accept: ["image/*"], maxSize: 1000000 })),
    name: l.string({ maxLength: 5000, maxGraphemes: 500 }),
    labels: l.optional(
      l.typedUnion(
        [l.typedRef<LabelDefs.SelfLabels>((() => LabelDefs.selfLabels) as any)],
        false,
      ),
    ),
    basicTheme: l.optional(
      l.ref<ThemeBasic.Main>((() => ThemeBasic.main) as any),
    ),
    description: l.optional(l.string({ maxLength: 30000, maxGraphemes: 3000 })),
    preferences: l.optional(l.ref<Preferences>((() => preferences) as any)),
  }),
);

export { main };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type;
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);

type Preferences = {
  $type?: "site.standard.publication#preferences";

  /**
   * Boolean which decides whether the publication should appear in discovery feeds.
   */
  showInDiscover?: boolean;
};

export type { Preferences };

const preferences = l.typedObject<Preferences>(
  $nsid,
  "preferences",
  l.object({ showInDiscover: l.optional(l.withDefault(l.boolean(), true)) }),
);

export { preferences };
