/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";
import * as ThemeColor from "./color.defs.js";

const $nsid = "site.standard.theme.basic";

export { $nsid };

/** Basic theme colors for a publication. */
type Main = {
  $type?: "site.standard.theme.basic";

  /**
   * Color used for content background.
   */
  background: ThemeColor.Rgb;

  /**
   * Color used for content text.
   */
  foreground: ThemeColor.Rgb;

  /**
   * Color used for links and button backgrounds.
   */
  accent: ThemeColor.Rgb;

  /**
   * Color used for button text.
   */
  accentForeground: ThemeColor.Rgb;
};

export type { Main };

/** Basic theme colors for a publication. */
const main = l.typedObject<Main>(
  $nsid,
  "main",
  l.object({
    background: l.ref<ThemeColor.Rgb>((() => ThemeColor.rgb) as any),
    foreground: l.ref<ThemeColor.Rgb>((() => ThemeColor.rgb) as any),
    accent: l.ref<ThemeColor.Rgb>((() => ThemeColor.rgb) as any),
    accentForeground: l.ref<ThemeColor.Rgb>((() => ThemeColor.rgb) as any),
  }),
);

export { main };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type;
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
