/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "site.standard.theme.color";

export { $nsid };

/** RGB color with red, green, and blue channels. */
type Rgb = {
  $type?: "site.standard.theme.color#rgb";

  /**
   * Red channel value.
   */
  r: number;

  /**
   * Green channel value.
   */
  g: number;

  /**
   * Blue channel value.
   */
  b: number;
};

export type { Rgb };

/** RGB color with red, green, and blue channels. */
const rgb = l.typedObject<Rgb>(
  $nsid,
  "rgb",
  l.object({
    r: l.integer({ minimum: 0, maximum: 255 }),
    g: l.integer({ minimum: 0, maximum: 255 }),
    b: l.integer({ minimum: 0, maximum: 255 }),
  }),
);

export { rgb };

/** RGBA color with red, green, blue, and alpha channels. */
type Rgba = {
  $type?: "site.standard.theme.color#rgba";

  /**
   * Red channel value.
   */
  r: number;

  /**
   * Green channel value.
   */
  g: number;

  /**
   * Blue channel value.
   */
  b: number;

  /**
   * Alpha (opacity) value, where 0 is transparent and 100 is opaque.
   */
  a: number;
};

export type { Rgba };

/** RGBA color with red, green, blue, and alpha channels. */
const rgba = l.typedObject<Rgba>(
  $nsid,
  "rgba",
  l.object({
    r: l.integer({ minimum: 0, maximum: 255 }),
    g: l.integer({ minimum: 0, maximum: 255 }),
    b: l.integer({ minimum: 0, maximum: 255 }),
    a: l.integer({ minimum: 0, maximum: 100 }),
  }),
);

export { rgba };
